// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prjxycapfsjjvxdzgkmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByanh5Y2FwZnNqanZ4ZHpna21wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mjk0MTYsImV4cCI6MjA2MDIwNTQxNn0.q4_q71UXPwI0xp4pdolT9bxBnCUGB-Uyghw0kBRY8K8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);